// Common 5-letter words for the game (curated for playability)
export const ANSWERS: string[] = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
  "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
  "alien", "align", "alike", "alive", "alley", "allow", "alone", "along",
  "alter", "amaze", "among", "ample", "angel", "anger", "angle", "angry",
  "anime", "ankle", "annex", "antic", "apart", "apple", "apply", "arena",
  "argue", "arise", "armor", "aroma", "arose", "array", "arrow", "aside",
  "asset", "attic", "audio", "audit", "avoid", "awake", "award", "aware",
  "awful", "bacon", "badge", "badly", "baker", "based", "basic", "basin",
  "basis", "batch", "beach", "beard", "beast", "began", "begin", "being",
  "belly", "below", "bench", "berry", "bible", "birth", "black", "blade",
  "blame", "bland", "blank", "blast", "blaze", "bleak", "bleed", "blend",
  "bless", "blind", "blink", "bliss", "block", "blood", "bloom", "blown",
  "board", "boast", "bonus", "boost", "booth", "bound", "brain", "brand",
  "brave", "bread", "break", "breed", "brick", "bride", "brief", "bring",
  "broad", "broke", "brook", "brown", "brush", "buddy", "build", "built",
  "bunch", "burst", "buyer", "cabin", "cable", "camel", "candy", "cargo",
  "carry", "catch", "cause", "cedar", "chain", "chair", "chalk", "champ",
  "chaos", "charm", "chart", "chase", "cheap", "check", "cheek", "cheer",
  "chess", "chest", "chief", "child", "chill", "china", "choir", "chunk",
  "civic", "civil", "claim", "clash", "class", "clean", "clear", "clerk",
  "click", "cliff", "climb", "cling", "cloak", "clock", "clone", "close",
  "cloth", "cloud", "clown", "coach", "coast", "color", "comet", "comic",
  "coral", "couch", "count", "coupe", "court", "cover", "crack", "craft",
  "crane", "crash", "crawl", "crazy", "cream", "creek", "crest", "crime",
  "crisp", "cross", "crowd", "crown", "crude", "crush", "curve", "cycle",
  "daily", "dance", "datum", "death", "debug", "debut", "decay", "delay",
  "delta", "demon", "dense", "depot", "depth", "derby", "devil", "diary",
  "dirty", "ditch", "dizzy", "dodge", "doubt", "dough", "draft", "drain",
  "drake", "drama", "drank", "drape", "drawl", "drawn", "dream", "dress",
  "dried", "drift", "drill", "drink", "drive", "drone", "drops", "drove",
  "drunk", "dryer", "dusty", "dwarf", "eager", "eagle", "early", "earth",
  "eaten", "eight", "elect", "elite", "embed", "ember",
  "empty", "enact", "enemy", "enjoy", "enter", "entry", "equal", "equip",
  "erode", "error", "essay", "ethic", "event", "every", "exact", "exert",
  "exile", "exist", "extra", "fable", "facet", "faith", "false",
  "fancy", "fatal", "fault", "feast", "fence", "ferry", "fetch", "fever",
  "fiber", "field", "fiery", "fifth", "fifty", "fight", "final", "first",
  "fixed", "flame", "flash", "flesh", "float", "flock", "flood", "floor",
  "flora", "flour", "fluid", "flush", "flute", "focal", "focus", "force",
  "forge", "forth", "forum", "found", "frame", "frank", "fraud",
  "fresh", "front", "frost", "froze", "fruit", "fully", "fungi", "fuzzy",
  "gauge", "genre", "ghost", "giant", "given", "gland", "glass", "gleam",
  "glide", "globe", "gloom", "glory", "gloss", "glove", "grace", "grade",
  "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grave",
  "great", "greed", "green", "greet", "grief", "grill", "grind", "gripe",
  "groan", "groom", "gross", "group", "grove", "growl", "grown", "guard",
  "guess", "guest", "guide", "guild", "guilt", "guise", "gulch", "gummy",
  "habit", "happy", "hardy", "harsh", "haste", "hasty", "hatch", "haunt",
  "haven", "heart", "heavy", "hedge", "heist", "hence", "herbs", "hiker",
  "hinge", "hobby", "honey", "honor", "horse", "hotel", "house", "human",
  "humor", "husky", "ideal", "image", "imply", "incur", "index", "indie",
  "infer", "inner", "input", "irony", "ivory", "jewel", "joint", "joker",
  "jolly", "judge", "juice", "juicy", "jumbo", "kebab", "khaki", "knack",
  "kneel", "knife", "knock", "known", "label", "labor", "lager", "lance",
  "large", "laser", "latch", "later", "laugh", "layer", "learn", "lease",
  "leave", "ledge", "legal", "lemon", "level", "lever", "light", "limit",
  "linen", "liner", "liver", "llama", "lobby", "local", "lodge", "logic",
  "login", "loose", "lorry", "lotus", "lover", "lower", "loyal", "lucky",
  "lunar", "lunch", "lunge", "lusty", "lyric", "macro", "magic", "major",
  "maker", "manor", "maple", "march", "marry", "marsh", "mason", "match",
  "mayor", "medal", "media", "mercy", "merge", "merit", "merry", "metal",
  "meter", "midst", "might", "miner", "minor", "minus", "mirth", "mixed",
  "model", "moist", "money", "month", "moral", "motel", "motor", "mound",
  "mount", "mourn", "mouse", "mouth", "movie", "muddy", "multi", "mural",
  "music", "naive", "named", "nerve", "never", "night", "noble", "noise",
  "north", "notch", "noted", "novel", "nurse", "nylon", "ocean", "olive",
  "onset", "opera", "orbit", "order", "organ", "other", "ought", "outer",
  "owned", "owner", "oxide", "ozone", "paint", "panel", "panic", "paper",
  "party", "pasta", "paste", "patch", "pause", "peace", "peach", "pearl",
  "pedal", "penny", "perch", "phase", "phone", "photo", "piano", "piece",
  "pilot", "pinch", "pixel", "pizza", "place", "plain", "plane", "plant",
  "plate", "plaza", "plead", "pluck", "plumb", "plume", "plump",
  "point", "polar", "porch", "poser", "pouch", "pound", "power", "press",
  "price", "pride", "prime", "print", "prior", "prize", "probe",
  "prone", "proof", "prose", "proud", "prove", "prowl", "psalm", "pulse",
  "punch", "pupil", "purse", "queen", "query", "quest", "queue",
  "quick", "quiet", "quota", "quote", "radar", "radio", "raise", "rally",
  "ranch", "range", "rapid", "ratio", "reach", "react", "ready", "realm",
  "rebel", "refer", "reign", "relax", "relay", "renal", "renew", "reply",
  "rider", "ridge", "rifle", "right", "rigid", "risky", "rival", "river",
  "robin", "robot", "rocky", "rogue", "roman", "roost", "rough", "round",
  "route", "royal", "rugby", "ruins", "ruler", "rural", "saint", "salad",
  "salon", "sauce", "scale", "scare", "scene", "scent", "scope", "score",
  "scout", "scrap", "sedan", "sense", "serum", "serve", "setup", "seven",
  "shade", "shaft", "shake", "shall", "shame", "shape", "share", "shark",
  "sharp", "shave", "sheep", "sheer", "sheet", "shelf", "shell", "shift",
  "shine", "shirt", "shock", "shore", "short", "shout", "shove", "shown",
  "sight", "sigma", "silly", "since", "sixth", "sixty", "sized", "skill",
  "skull", "slash", "slate", "sleep", "slice", "slide", "slope", "smart",
  "smell", "smile", "smoke", "snake", "snare", "solar", "solid", "solve",
  "sorry", "sound", "south", "space", "spare", "spark", "spawn", "speak",
  "spear", "speed", "spell", "spend", "spent", "spice", "spike", "spine",
  "spite", "split", "spoke", "spoon", "sport", "spray", "squad", "stack",
  "staff", "stage", "stain", "stake", "stale", "stall", "stamp", "stand",
  "stare", "start", "state", "stays", "stead", "steal", "steam", "steel",
  "steep", "steer", "stern", "stick", "stiff", "still", "sting", "stock",
  "stoic", "stone", "stood", "stool", "store", "storm", "story", "stout",
  "stove", "strap", "straw", "stray", "strip", "stuck", "study", "stuff",
  "style", "sugar", "suite", "sunny", "super", "surge", "swamp", "swarm",
  "swear", "sweat", "sweep", "sweet", "swept", "swift", "swing", "swirl",
  "sword", "swore", "sworn", "syrup", "table", "taste", "taxes", "teach",
  "teeth", "tempo", "tends", "tenor", "tenth", "thank", "theme", "there",
  "thick", "thief", "thing", "think", "third", "thorn", "those", "three",
  "threw", "throw", "thumb", "tidal", "tiger", "tight", "timer", "tired",
  "title", "toast", "token", "total", "touch", "tough", "towel", "tower",
  "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash",
  "treat", "trend", "trial", "tribe", "trick", "tried", "troop", "truck",
  "truly", "trump", "trunk", "trust", "truth", "tuner", "twist", "ultra",
  "uncle", "under", "union", "unite", "unity", "until", "upper", "upset",
  "urban", "usage", "usual", "utter", "valid", "value", "valve", "vapor",
  "vault", "venue", "verse", "video", "vigor", "viral", "virus", "visit",
  "vista", "vital", "vivid", "vocal", "vodka", "voice", "voter", "wagon",
  "waste", "watch", "water", "weary", "weave", "wedge", "weird", "whale",
  "wheat", "wheel", "where", "which", "while", "white", "whole", "whose",
  "wider", "witch", "woman", "world", "worry", "worse", "worst", "worth",
  "wound", "wrath", "write", "wrong", "wrote", "yacht", "yield", "young",
  "youth", "zebra",
];

// Larger set of valid guesses (includes answers + additional common words)
export const VALID_GUESSES: Set<string> = new Set([
  ...ANSWERS,
  "aahed", "aalii", "aback", "abaft", "abase", "abash", "abate", "abbey",
  "abbot", "abhor", "abide", "abler", "abode", "abort", "abyss", "acorn",
  "acrid", "added", "adder", "adept", "adieu", "admin", "adobe", "adore",
  "adorn", "aegis", "afoot", "afoul", "agave", "aging", "aglow", "agony",
  "aisle", "algae", "alibi", "allay", "allot", "alloy", "aloft", "alpha",
  "altar", "amber", "amend", "amino", "amiss", "amity", "amuse", "angel",
  "angry", "angst", "anime", "annex", "annoy", "antic", "anvil", "aorta",
  "aptly", "arbor", "ardor", "atoll", "atone", "augur", "avian",
  "await", "awash", "axial", "axiom", "azure", "badge", "bagel", "baggy",
  "barge", "baron", "basil", "batty", "bayou", "beady", "beast", "beech",
  "befog", "begun", "beige", "being", "belch", "belle", "beret", "berry",
  "beset", "bigot", "billy", "bingo", "biome", "birch", "bison", "bitty",
  "blare", "blase", "blimp", "bliss", "blitz", "bloat", "bloke", "blond",
  "bluff", "blunt", "blurb", "blurt", "blush", "bogey", "boggy",
  "boner", "bongo", "bonus", "booby", "booze", "boozy", "borax", "bossy",
  "botch", "bound", "bowed", "bowel", "boxer", "brace", "braid", "brake",
  "brash", "brass", "brawl", "brawn", "briar", "bribe", "brine", "brink",
  "briny", "brisk", "brood", "brook", "broth", "brunt", "brute", "budge",
  "buggy", "bugle", "bulge", "bulky", "bully", "bunch", "bunny", "burly",
  "burnt", "butch", "cadet", "cairn", "camel", "cameo", "candy", "canny",
  "canoe", "caper", "caput", "carat", "cargo", "carol", "carry", "catch",
  "caulk", "cavil", "cedar", "chase", "cheek", "cheer", "chess", "chick",
  "chief", "china", "chirp", "choke", "chord", "chose", "chump", "chunk",
  "churn", "cider", "cigar", "cinch", "circa", "civic", "claim", "clamp",
  "clang", "clank", "clasp", "clean", "clear", "clerk", "cleft",
  "click", "cliff", "climb", "cling", "cloak", "clone", "close", "cloth",
  "cloud", "clout", "clove", "clown", "cobra", "cocoa", "colon",
  "combo", "comic", "comma", "conch", "coral", "corgi", "count", "coupe",
  "court", "cover", "covet", "crack", "crane", "crank", "crash", "crass",
  "crate", "crave", "crawl", "craze", "crazy", "creak", "cream", "creep",
  "crest", "crick", "crime", "crimp", "crisp", "croak", "crock", "crook",
  "croup", "crown", "crude", "cruel", "crumb", "crush", "crust", "cubic",
  "cupid", "curly", "curry", "curse", "curve", "cycle", "cynic",
  "daddy", "daily", "dairy", "daisy", "dance", "dandy", "datum", "debug",
  "decal", "decay", "decor", "decoy", "decry", "deity", "delay", "delta",
  "delve", "demon", "demur", "denim", "dense", "depot", "depth", "derby",
  "deter", "detox", "deuce", "devil", "diary", "digit", "dingo",
  "dingy", "dirge", "dirty", "disco", "ditto", "ditty", "diver", "dizzy",
  "dodge", "dolly", "donor", "donut", "dopey", "doubt", "dough", "dowdy",
  "dowel", "draft", "drain", "drape", "dream", "dress", "drift", "drill",
  "drink", "drive", "droit", "droll", "drone", "drool", "droop", "drops",
  "dross", "drove", "drown", "drunk", "dryer", "dryly", "duchy", "dully",
  "dummy", "dunce", "dusty", "dutch", "duvet", "dwarf", "dwell", "dying",
  "eager", "eagle", "early", "earth", "easel", "eaten", "eater", "ebony",
  "edict", "eerie", "eight", "elder", "elect", "elfin", "elite", "elope",
  "elude", "email", "ember", "emcee", "emoji", "empty", "enact", "endow",
  "enemy", "enjoy", "ennui", "ensue", "enter", "entry", "envoy", "epoch",
  "equal", "equip", "erase", "erode", "error", "erupt", "essay", "ether",
  "ethic", "evade", "event", "every", "evict", "evoke", "exact", "exalt",
  "excel", "exert", "exile", "exist", "expat", "expel", "extra", "exude",
  "exult", "fable", "facet", "fairy", "faith", "false", "fancy", "fatal",
  "fatty", "fault", "fauna", "feast", "feign", "feint", "fella", "felon",
  "femur", "fence", "ferry", "fetal", "fetch", "fetid", "fetus", "fever",
  "fiber", "fibre", "ficus", "field", "fiend", "fiery", "fifth", "fifty",
  "fight", "filmy", "filth", "final", "finch", "first", "fishy", "fixer",
  "fizzy", "fjord", "flack", "flail", "flair", "flake", "flaky", "flame",
  "flank", "flare", "flask", "flesh", "flick", "flier", "fling", "flint",
  "float", "flock", "flood", "floor", "floss", "flour", "flout", "flown",
  "fluff", "fluid", "fluke", "flung", "flunk", "flush", "flute", "flyby",
  "foamy", "focal", "foggy", "folio", "folly", "foray", "force", "forge",
  "forgo", "forte", "forth", "forum", "found", "foxes", "foyer", "frail",
  "frame", "frank", "fraud", "freak", "freed", "fresh", "friar", "fried",
  "frill", "frisk", "fritz", "frock", "frond", "front", "frost", "frown",
  "froze", "fruit", "fully", "fungi", "funky", "funny", "furry",
  "fussy", "fuzzy", "gamma", "gaudy", "gauge", "gaunt", "gauze", "gavel",
  "geeky", "genie", "genre", "ghost", "giant", "giddy", "given", "giver",
  "gizmo", "gland", "glare", "glass", "glaze", "gleam", "glean", "glide",
  "glint", "gloat", "globe", "gloom", "glory", "gloss", "glove", "glyph",
  "gnash", "golem", "golly", "goose", "gorge", "gouge", "gourd", "grace",
  "grade", "graft", "grail", "grain", "grand", "grant", "grape", "graph",
  "grasp", "grass", "grate", "grave", "gravy", "graze", "great", "greed",
  "green", "greet", "grief", "grill", "grime", "grimy", "grind", "gripe",
  "groan", "groin", "groom", "grope", "gross", "group", "grout", "grove",
  "growl", "grown", "gruel", "gruff", "grump", "grunt", "guava", "guess",
  "guest", "guide", "guild", "guilt", "guise", "gulch", "gummy", "guppy",
  "gusto", "gusty",
  "habit", "haiku", "happy", "hardy", "harem", "harpy", "harry", "harsh",
  "haste", "hasty", "hatch", "haunt", "haven", "hazel", "heady", "heart",
  "heave", "heavy", "hedge", "hefty", "heist", "helix", "hello", "hence",
  "herbs", "heron", "hiker", "hilly", "hinge", "hippo", "hitch", "hoard",
  "hobby", "homer", "honey", "honor", "horse", "hotel", "hound", "house",
  "hovel", "hover", "howdy", "human", "humid", "humor", "humps", "humus",
  "hunch", "husky", "hyena", "hyper",
  "icily", "icing", "ideal", "idiom", "idiot", "image", "imbue", "impel",
  "imply", "inane", "incur", "index", "indie", "inept", "inert", "infer",
  "ingot", "inner", "input", "inter", "intro", "ionic", "irate", "irony",
  "ivory", "jaunt", "jazzy", "jelly", "jenny", "jerky", "jewel", "jiffy",
  "jimmy", "joint", "joker", "jolly", "joust", "judge", "juice", "juicy",
  "jumbo", "jumpy", "junco", "juror",
  "kayak", "kebab", "khaki", "kinky", "kiosk", "knack", "knead", "kneel",
  "knelt", "knife", "knock", "knoll", "known",
  "label", "labor", "lager", "lance", "lanky", "lapse", "large", "larva",
  "laser", "lasso", "latch", "later", "lathe", "latte", "laugh", "layer",
  "leach", "leafy", "leaky", "learn", "lease", "least", "leave", "ledge",
  "leech", "legal", "leggy", "lemon", "lemur", "level", "lever", "libel",
  "light", "lilac", "limbo", "limit", "linen", "liner", "lingo",
  "lipid", "liver", "livid", "llama", "lobby", "local", "locus", "lodge",
  "lofty", "logic", "login", "loopy", "loose", "lorry", "loser", "lotus",
  "lousy", "lover", "lower", "loyal", "lucid", "lucky", "lumen", "lumpy",
  "lunar", "lunch", "lunge", "lurch", "lusty", "lying", "lymph", "lyric",
]);
